language: python
jobs:
    include:
        - python: 3.5
        - python: 3.6
        - python: 3.7
          dist: xenial
          sudo: true
        - python: 3.8-dev
          dist: xenial
          sudo: true
        - python: nightly
          dist: xenial
          sudo: true
matrix:
    allow_failures:
        - python: nightly
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - coverage run --branch --source lectocal -m unittest -v
after_success:
  - coverage report
  - coveralls