# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/lectocal
    docker:
      - image: circleci/python:3.7.0

    steps:
      - checkout
      - run: pip install pipenv
      - run: pipenv install --dev
      - persist_to_workspace:
          root: .
          paths: '*'
  test:
    working_directory: ~/lectocal
    docker:
      - image: circleci/python:3.7.0
    
    steps:
      - attach_workspace:
          at: ~/lectocal
      - run: pipenv run coverage run --branch --source lectocal -m unittest -v
      - run: pipenv run coverage report
      - run: pipenv run coveralls
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
